services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
        # fetching services directly from the container via $container->get() won't work.
        # The best practice is to be explicit about your dependencies anyway.
        bind:
            $pnTwitchClientId: '%env(string:PN_TWITCH_CLIENT_ID)%'
            $pnTwitchClientSecret: '%env(string:PN_TWITCH_CLIENT_SECRET)%'
            $pbTwitchBroadcasterId: '%env(int:PN_TWITCH_BROADCASTER_ID)%'
    ProjetNormandie\TwitchBundle\:
        resource: '../../*'
        exclude: '../../{Admin,DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
    ProjetNormandie\TwitchBundle\DataProvider\TwitchItemDataProvider:
        # Uncomment only if autoconfiguration is disabled
        tags: [ 'api_platform.item_data_provider' ]



