services:
  _defaults:
    autowire: true
    autoconfigure: true

  ProjetNormandie\TwitchBundle\:
    resource: '../src/*'
    exclude: '../src/{Admin,DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
